before_install:
- openssl aes-256-cbc -k "$super_secret_password" -in hangout_api/tests/resources/credentials.yaml.enc -out hangout_api/tests/resources/credentials.yaml -d
- sudo apt-get update --fix-missing
- sudo apt-get install -qq wget python-dev python3-dev
- sudo apt-get install -qq xserver-xephyr scrot xvfb tightvncserver
- wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
- sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
- sudo apt-get install -qq google-chrome-stable
install:
- pip install setuptools --upgrade
- python bootstrap.py -c travis.cfg
- bin/buildout -N -q -t 10 -c travis.cfg
python:
- 2.7
- 3.3
- 3.4
language: python
script:
- bin/test
after_success:
- bin/coveralls
env:
  global:
    secure: J0qrAUbwA63b8NGwYWH6J68AADrZ//z5lnegS5NT5BbB4B7mHFz/A9yaj4MY87KaEqjyXgcbfFAd7z+zRDJGiYT7P12UxPL6hql6aj8frBxU8V++SO9v0vgVBBAMms2OSe+7pxoOfM11z6w9gJAm9I2494lL0amWR7yqn3qMe0M=
