---
before_install:
    - sudo apt-get install -qq wget python-dev python3-dev xvfb xserver-xephyr tightvncserver python-imaging scrot
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
    - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
    - sudo apt-get update
    - sudo apt-get install -qq google-chrome-stable

install:
    - pip install setuptools --upgrade
    - python bootstrap.py
    - bin/buildout -N -q -t 10
python:
    - 2.7
    - 3.3
language: python
script: bin/nosetests --no-skip
